PIN-3574 Add eserviceId and consumerId to PurposeUpdateContent
pagopa/interop-be-purpose-management pull request #204
Opened 2023-07-17 11:11 UTC by nttdata-rtorsoli

2023-07-18 13:06 UTC, beetlecrunch approved these changes

2023-07-26 08:13 UTC, TonioGela approved these changes

2023-07-26 09:43 UTC, galales requested changes

2023-07-26 09:43 UTC, galales commented on src/main/resources/interface-specification.yml
> +          format: uuid
`consumerId` should not be changed

2023-07-26 12:41 UTC, galales approved these changes

2023-07-27 12:39 UTC, beetlecrunch approved these changes

2023-07-28 09:03 UTC, merged