PIN-3691 When create a purpose a draft version wil lbe created at the same time
pagopa/interop-be-purpose-management pull request #205
Opened 2023-08-03 07:32 UTC by nttdata-rtorsoli

2023-08-03 07:49 UTC, TonioGela approved these changes

2023-08-03 09:31 UTC, galales requested changes

2023-08-03 09:31 UTC, galales commented on src/main/scala/it/pagopa/interop/purposemanagement/api/impl/PurposeApiServiceImpl.scala
> +        .map(_.toAPI)
these should be replaced with a single call.
The `CreatePurpose` takes a full purpose, in which you can attach the version

2023-08-03 13:12 UTC, galales commented on src/test/scala/it/pagopa/interop/purposemanagement/provider/PurposeVersionSpec.scala
> -          result <- createPurposeVersion(purposeId, versionId, versionSeed)
this is testing the creation of a single new version, it should not be changed to the creation of the purpose + first version

2023-08-03 13:12 UTC, galales commented on src/test/scala/it/pagopa/interop/purposemanagement/provider/PurposeVersionSpec.scala
> -      val versionSeed     = PurposeVersionSeed(riskAnalysis = Some(riskAnalysisDoc), dailyCalls = 100)
same, this is testing the creation of a version with the risk analysis document. It should be kept

2023-08-03 13:12 UTC, galales commented on src/test/scala/it/pagopa/interop/purposemanagement/provider/PurposeVersionStateChangeSpec.scala
> -    "succeed when risk analysis is added at creation" in {
any reason why this has been deleted?
We should still be able to load risk analysis at creation and then activate

2023-08-03 13:12 UTC, galales commented on src/test/scala/it/pagopa/interop/purposemanagement/provider/PurposeVersionStateChangeSpec.scala
> -      val (version, result) = response.futureValue
this is testing that on activation, those (and only) specific fields are updated.
This is why it was returning the created version and the activated version.
With this update, if a new field that we do not expect is changed the test will succeed.

This should be rollbacked

2023-08-03 13:12 UTC, galales commented on src/test/scala/it/pagopa/interop/purposemanagement/provider/PurposeVersionStateChangeSpec.scala
> -      val (version, result) = response.futureValue
same for rollback

2023-08-03 13:12 UTC, galales commented on src/test/scala/it/pagopa/interop/purposemanagement/provider/PurposeVersionStateChangeSpec.scala
> -      val (version, result) = response.futureValue
same for rollback

2023-08-03 13:12 UTC, galales commented on src/test/scala/it/pagopa/interop/purposemanagement/provider/PurposeVersionStateChangeSpec.scala
> -      val (version, result) = response.futureValue
same for rollback

2023-08-03 13:12 UTC, galales commented on src/test/scala/it/pagopa/interop/purposemanagement/provider/PurposeVersionStateChangeSpec.scala
> -      val (version, result) = response.futureValue
same for rollback

2023-08-03 13:12 UTC, galales commented on src/main/scala/it/pagopa/interop/purposemanagement/model/persistence/Adapters.scala
> +          createdAt = dateTimeSupplier.get(),
this is subtle but very useful when troubleshooting:
may you create the timestamp with `dateTimeSupplier.get()` just once and use the same value in both purpose and version?

2023-08-04 12:11 UTC, galales approved these changes

2023-08-07 08:00 UTC, merged