pin-1385: CQRS projection
pagopa/interop-be-purpose-management pull request #82
Opened 2022-05-06 16:06 UTC by galales

See comments in https://github.com/pagopa/interop-be-purpose-management/pull/135

2022-05-11 15:43 UTC, TonioGela requested changes

2022-05-13 13:17 UTC, ubaldop approved these changes

2022-05-13 13:41 UTC, TonioGela approved these changes

2022-05-31 16:10 UTC, beetlecrunch approved these changes

2022-07-07 07:28 UTC, TonioGela commented on src/main/scala/it/pagopa/interop/purposemanagement/model/persistence/projection/PurposeCqrsProjection.scala
> +  private def eventHandler(collection: MongoCollection[Document], event: Event): PartialMongoAction = event match {
😍

2022-08-23 15:58 UTC, merged